// Generated by dts-bundle-generator v9.5.1

import * as React$1 from 'react';

export interface SerializedPropertyValue {
	value: unknown;
	type: string;
}
export interface NodeDto {
	address: string;
	aggregateId: string;
	nodeType: string;
	name: string | null;
	/**
	 * Display label computed server-side (the canonical Neos node label: node
	 * type label expression, tethered-collection label, or nodeType/name
	 * fallback), with HTML entities decoded to plain text. Prefer this over
	 * deriving a label from properties on the client.
	 */
	label: string;
	classification: string;
	/**
	 * Whether the node has visible children; when the response came from a
	 * nodeTypes-filtered children/descendants request, the same filter applies
	 * (a document listing reports "has document children").
	 */
	hasChildren: boolean;
	workspace: string;
	dimensionSpacePoint: Record<string, string>;
	originDimensionSpacePoint: Record<string, string>;
	properties: Record<string, SerializedPropertyValue>;
	tags: {
		all: string[];
		inherited: string[];
	};
	timestamps: {
		created: string;
		originalCreated: string;
		lastModified: string | null;
		originalLastModified: string | null;
	};
}
export interface Site {
	name: string;
	nodeName: string;
	/**
	 * The site node's aggregate id - used to scope workspace publish/discard to
	 * this site. null if the site node does not exist in the current subgraph.
	 */
	aggregateId: string | null;
	/** null if the site node does not exist in the current subgraph */
	nodeAddress: string | null;
}
/**
 * An edit that happened elsewhere (preview, inspector, context menu); token
 * distinguishes repeats. Usually one address; structural edits (a move)
 * touch several, and ALL_NODES means the whole workspace content changed.
 */
export interface NodeEdit {
	addresses: string[];
	token: number;
}
/**
 * App state and actions exposed to panels. Panels (built-in and third-party
 * alike) render without props and read everything from this context, so a
 * panel component is self-contained and registerable. Keep this surface
 * deliberate - it is the beginning of the plugin API.
 */
export type StudioContextValue = {
	/** The active site, or null while sites load. */
	site: Site | null;
	/** The active workspace's name, or null while workspaces load. */
	workspaceName: string | null;
	/** The document shown in the preview and selected in the document tree. */
	selectedDocument: NodeDto | null;
	/** The node under inspection - a document or a content node. */
	inspectedNode: NodeDto | null;
	/** The last inline edit from the preview; refreshes outliner labels. */
	lastEdit: NodeEdit | null;
	/** Bumped to reload the preview iframe after edits made outside of it. */
	previewReloadToken: number;
	/**
	 * The last edit that wants just its node's element refreshed in the preview
	 * (out-of-band render + DOM swap instead of an iframe reload). The token
	 * distinguishes successive edits of the same address.
	 */
	previewElementUpdate: {
		address: string;
		token: number;
	} | null;
	/** Select a document (also inspects it). */
	selectDocument: (node: NodeDto) => void;
	/** Inspect a node without changing the selected document. */
	inspectNode: (node: NodeDto) => void;
	/** Fetch and inspect the node at this address (e.g. a preview click). */
	inspectAddress: (address: string) => void;
	/**
	 * Follow a link to another document (a preview navigation): show the target
	 * document, switching the active dimension to match it when they differ.
	 */
	navigateToNode: (address: string) => void;
	/**
	 * Report inline edits made inside the preview: bumps outliner labels without
	 * the refetch/reload the inspector path needs (the iframe already rendered
	 * the change live).
	 */
	reportInlineEdit: (addresses: string[]) => void;
	/**
	 * Report that a property edit for this address was persisted. reload
	 * mirrors the property's configuration and defaults to 'page' (full iframe
	 * reload); 'element' re-renders just the node's element out-of-band
	 * (ui.reloadIfChanged); 'none' leaves the preview alone - the change does
	 * not affect the rendered page. Trees and the inspector always refresh.
	 */
	nodeEdited: (address: string, options?: {
		reload?: "page" | "element" | "none";
	}) => void;
	/**
	 * Report a structural change (e.g. a drag-and-drop move) affecting several
	 * addresses at once - their child lists are refreshed in the trees and the
	 * preview reloads, without the single-address inspector refetch nodeEdited
	 * does.
	 */
	nodesEdited: (addresses: string[]) => void;
	/**
	 * Report that the workspace's content changed wholesale (published -
	 * which rebases the workspace - or discarded): every cached node read,
	 * tree item and the preview are refreshed.
	 */
	workspaceContentChanged: () => void;
};
export declare function useStudio(): StudioContextValue;
/**
 * Shared geometry for floating panel groups: viewport clamping and
 * edge/corner resizing.
 */
export type PanelRect = {
	x: number;
	y: number;
	width: number;
	height: number;
};
/**
 * The docked homes a group can occupy: the left `sidebar`, the big center
 * `main` area, and the optional right `secondary` sidebar. Each is an
 * independent vertical stack of groups.
 */
export type DockRegion = "sidebar" | "main" | "secondary";
/**
 * The panel registry: every panel - built-in or third-party - registers here
 * and the panel system renders whatever is registered. Panels register at any
 * time (built-ins before mount, plugins possibly after); the layout
 * re-normalizes when the set changes, so new panels appear at their default
 * placement and panels of unloaded plugins vanish without disturbing the
 * user's arrangement (their stored layout entry is simply dropped).
 */
export type PanelPlacement = 
/**
 * Docked in a region (sidebar/main/secondary), appended below existing
 * groups. Panels default-placed in the same pass that share a `group` key
 * join one group (as tabs) instead of each opening their own.
 */
{
	kind: "dock";
	region: DockRegion;
	group?: string;
}
/** Floating; `rect` is evaluated lazily against the live viewport. */
 | {
	kind: "floating";
	rect: () => PanelRect;
};
export type PanelDefinition = {
	/** Unique id, persisted in layouts. Third-party panels should namespace ('vendor.package:panel'). */
	id: string;
	/** Tab label. */
	title: string;
	/** Panel body. Receives no props - read app state via context (e.g. useStudio()). */
	component: React$1.ComponentType;
	/** Where the panel appears when absent from the stored layout. */
	defaultPlacement: PanelPlacement;
};
declare class PanelRegistry {
	private definitions;
	private listeners;
	private snapshot;
	/** Registering an already-known id replaces it, so HMR and plugin reloads stay idempotent. */
	register(definition: PanelDefinition): void;
	unregister(id: string): void;
	get(id: string): PanelDefinition | undefined;
	/** Stable snapshot in registration order - changes identity only on (un)register. */
	getAll(): PanelDefinition[];
	subscribe(listener: () => void): () => void;
	private emit;
}
/**
 * The node property editor registry: every editor - built-in or third-party -
 * registers here under the editor identifier that node type configuration
 * references (ui.inspector.editor / ui.editor, e.g.
 * "Neos.Neos/Inspector/Editors/TextFieldEditor"). Both places that edit node
 * properties - the inspector and the node creation dialogs - resolve their
 * controls through this one registry, so an editor written once works in both,
 * and a plugin that registers a custom editor lights up everywhere.
 *
 * Modelled on the panel registry (see features/panels/registry.ts): a small
 * observable store, register-replaces-by-id for idempotent HMR and plugin
 * reloads, and a stable snapshot for React.
 */
/** What an editor is editing: a node property (inspector) or a creation-dialog element. */
export interface PropertyEditorSubject {
	/** Property / element name. */
	name: string;
	/** The type from node type configuration, e.g. "string", "integer", "reference". */
	type: string;
	/** Resolved, human-readable label. */
	label: string;
}
/**
 * The props every property editor receives. Editors own their transient state
 * (a text field keeps what is being typed; the `value` prop only seeds it, so
 * hosts remount on a subject change to reset), and report outward through two
 * callbacks. The split is what lets one editor serve both hosts:
 *
 *  - `onCommit` fires at a natural commit boundary (blur, Enter, a discrete
 *    pick) and carries the value worth keeping. The inspector persists here;
 *    it is the essential signal, so every editor must call it.
 *  - `onChange` fires on every keystroke-level change, before a commit, so a
 *    host tracking a live working copy stays current. The creation dialog
 *    needs this - its required-field validation gates the Create button, which
 *    would otherwise lag a click behind commit-on-blur. Editors with no
 *    distinct editing phase (a checkbox, a select) need only call `onCommit`.
 *
 * The host decides what those mean: the inspector auto-saves on commit, the
 * creation dialog folds every change into the draft it submits on Create. The
 * difference between the hosts lives entirely in the host, never in the editor.
 */
export interface PropertyEditorProps {
	/** The property / element being edited. */
	subject: PropertyEditorSubject;
	/** The current value, already unwrapped from any transport envelope. Seeds the editor's state; `undefined` means unset, `null` clears it. */
	value: unknown;
	/** Commit a value worth keeping (blur, Enter, a discrete pick). Required - the inspector persists here. */
	onCommit: (value: unknown) => void;
	/** Report a live, pre-commit value (per keystroke). Optional - only hosts tracking a working copy (the creation dialog) consume it. */
	onChange?: (value: unknown) => void;
	/** The editor's configuration - ui.inspector.editorOptions / ui.editorOptions for this property. */
	options: Record<string, unknown>;
	/** Focus on mount; the host sets this for the first field of a form. */
	autoFocus?: boolean;
	/**
	 * The current value fails validation (see validators/registry.ts). The host
	 * renders the error message(s) below the editor either way; editors that
	 * can should additionally mark their control (aria-invalid on an input
	 * turns its border red). Purely presentational - validation itself runs in
	 * the hosts, never in editors.
	 */
	invalid?: boolean;
	/**
	 * The address of the node being edited, when it already exists (the
	 * inspector). Absent in the node creation dialog, where the node does not
	 * exist yet. Editors that operate on the node itself - e.g. the node type
	 * switcher, which resolves the parent's allowed child types - need it, and
	 * degrade gracefully without it.
	 */
	nodeAddress?: string;
}
export type PropertyEditorComponent = React$1.ComponentType<PropertyEditorProps>;
export interface PropertyEditorDefinition {
	/**
	 * The editor identifier as referenced from node type configuration, e.g.
	 * "Neos.Neos/Inspector/Editors/TextFieldEditor". Third-party editors should
	 * namespace their own ids ('Vendor.Package/Editors/Color').
	 */
	id: string;
	/** The control. */
	component: PropertyEditorComponent;
	/**
	 * Whether the editor renders the property label itself - e.g. a checkbox
	 * with its label beside it. When true, the host omits its own label and
	 * leaves label placement to the editor, which reads subject.label. Defaults
	 * to false: the host renders the label above the control.
	 */
	rendersOwnLabel?: boolean;
}
declare class PropertyEditorRegistry {
	private definitions;
	private listeners;
	private snapshot;
	/** Registering an already-known id replaces it, so HMR and plugin reloads stay idempotent. */
	register(definition: PropertyEditorDefinition): void;
	unregister(id: string): void;
	/** The component registered for an editor id, or undefined - the host renders a read-only fallback for unknown editors. */
	get(id: string | null | undefined): PropertyEditorComponent | undefined;
	/** The full definition for an editor id (component + metadata), or undefined. */
	getDefinition(id: string | null | undefined): PropertyEditorDefinition | undefined;
	/** Stable snapshot in registration order - changes identity only on (un)register. */
	getAll(): PropertyEditorDefinition[];
	subscribe(listener: () => void): () => void;
	private emit;
}
/**
 * The inspector view registry: read-only widgets that node type configuration
 * places between inspector properties (ui.inspector.views), registered under
 * the view identifier the configuration references (e.g.
 * "Neos.Neos/Inspector/Views/Data/TableView"). Modelled on the property
 * editor registry (features/inspector/editors/registry.ts): a small observable
 * store, register-replaces-by-id for idempotent HMR and plugin reloads, and a
 * stable snapshot for React - the same seam third-party views plug into.
 */
export interface InspectorViewProps {
	/** The node being inspected. */
	node: NodeDto;
	/** Resolved, human-readable label of the view. */
	label: string;
	/** The view's configuration - ui.inspector.views.*.viewOptions. */
	options: Record<string, unknown>;
}
export type InspectorViewComponent = React$1.ComponentType<InspectorViewProps>;
export interface InspectorViewDefinition {
	/** The view identifier as referenced from node type configuration. */
	id: string;
	component: InspectorViewComponent;
}
declare class InspectorViewRegistry {
	private definitions;
	private listeners;
	private snapshot;
	/** Registering an already-known id replaces it, so HMR and plugin reloads stay idempotent. */
	register(definition: InspectorViewDefinition): void;
	unregister(id: string): void;
	getDefinition(id: string | null | undefined): InspectorViewDefinition | undefined;
	/** Stable snapshot in registration order - changes identity only on (un)register. */
	getAll(): InspectorViewDefinition[];
	subscribe(listener: () => void): () => void;
	private emit;
}
/**
 * The property validator registry: every validator - built-in or third-party -
 * registers here under the validator identifier that node type configuration
 * references (the keys of a property's / creation-dialog element's
 * `validation` block, e.g. "Neos.Neos/Validation/NotEmptyValidator"). Both
 * places that edit node properties - the inspector and the node creation
 * dialogs - run their values through this one registry, so a validator written
 * once works in both, and a plugin that registers a custom validator lights up
 * everywhere.
 *
 * Modelled on the property editor registry (see editors/registry.ts): a small
 * observable store, register-replaces-by-id for idempotent HMR and plugin
 * reloads, and a stable snapshot for React.
 */
/**
 * A validator checks one value against its configured options and returns
 * either null (valid) or a human-readable error message. Validators never
 * enforce presence unless that is their single job (NotEmptyValidator): an
 * empty value passes every other validator, matching Flow's server-side
 * semantics - "required" and "well-formed" are separate declarations.
 */
export type ValidatorFunction = (value: unknown, options: Record<string, unknown>) => string | null;
export interface ValidatorDefinition {
	/**
	 * The validator identifier as referenced from node type configuration, e.g.
	 * "Neos.Neos/Validation/NotEmptyValidator". Third-party validators should
	 * namespace their own ids ('Vendor.Package/Validation/Iban').
	 */
	id: string;
	/** The check. */
	validate: ValidatorFunction;
}
declare class ValidatorRegistry {
	private definitions;
	private listeners;
	private snapshot;
	/** Registering an already-known id replaces it, so HMR and plugin reloads stay idempotent. */
	register(definition: ValidatorDefinition): void;
	unregister(id: string): void;
	/** The definition registered for a validator id, or undefined - unknown validators are skipped (with a console warning) when validating. */
	get(id: string | null | undefined): ValidatorDefinition | undefined;
	/** Stable snapshot in registration order - changes identity only on (un)register. */
	getAll(): ValidatorDefinition[];
	subscribe(listener: () => void): () => void;
	private emit;
}
/**
 * The link type registry: each entry contributes one tab to the Link Editor
 * dialog (see LinkEditorDialog.tsx) - a way of producing an href. The built-in
 * types (document, asset, external URL, e-mail) register here exactly like a
 * third-party plugin would register a tab for its own link source (an external
 * DAM, a shop's product catalogue, ...).
 *
 * Modelled on the property editor registry (see features/inspector/editors/
 * registry.ts): a small observable store, register-replaces-by-id for
 * idempotent HMR and plugin reloads, and a stable snapshot for React.
 */
/** The props a link type tab receives from the Link Editor dialog. */
export interface LinkTypeTabProps {
	/**
	 * The current href draft for this tab: the edited link's href when it
	 * belongs to this type (matches() returned true), a draft the tab reported
	 * earlier this session, or null when there is nothing yet. The tab seeds its
	 * controls from it.
	 */
	href: string | null;
	/**
	 * Report the tab's result. An href when the tab's state amounts to a
	 * complete link (a picked document, a typed URL), null while it is
	 * incomplete - the dialog's Apply button follows.
	 */
	onChange: (href: string | null) => void;
}
export interface LinkTypeDefinition {
	/**
	 * Stable id, also the tab's identity. Third-party types should namespace
	 * their own ids ('Vendor.Package/LinkTypes/Product').
	 */
	id: string;
	/** The tab's label. */
	label: string;
	/** An icon rendered before the label (and to mark link values of this type). */
	icon?: React$1.ReactNode;
	/** The tab's UI. */
	component: React$1.ComponentType<LinkTypeTabProps>;
	/**
	 * Whether an existing href belongs to this type - decides which tab an
	 * edited link opens on, and which type's icon marks a stored value.
	 */
	matches: (href: string) => boolean;
	/**
	 * The type hrefs fall back to when no type matches (the external-URL tab):
	 * it can display any href verbatim for the user to correct. At most one
	 * registered type should set this.
	 */
	isFallback?: boolean;
}
declare class LinkEditorRegistry {
	private definitions;
	private listeners;
	private snapshot;
	/** Registering an already-known id replaces it, so HMR and plugin reloads stay idempotent. */
	register(definition: LinkTypeDefinition): void;
	unregister(id: string): void;
	/** Stable snapshot in registration order - changes identity only on (un)register. */
	getAll(): LinkTypeDefinition[];
	/**
	 * The type an href belongs to: the first registered type that matches it,
	 * the fallback type otherwise (or the first registered as a last resort).
	 */
	match(href: string): LinkTypeDefinition | undefined;
	subscribe(listener: () => void): () => void;
	private emit;
}
/**
 * The settings-dialog registry: Studio replaces the classic Neos backend
 * modules with large, near-screen-filling modal dialogs.
 *
 * The {@link settingsDialogRegistry} holds *settings sections*. They all share
 * one Settings modal whose left-hand subnavigation lists every registered
 * section (users, sites, workspaces, ...); picking one renders it in the modal
 * body. Built-ins and third-party plugins register the same way.
 *
 * It is modelled on the panel and property-editor registries (see
 * features/panels/registry.ts and features/inspector/editors/registry.ts): a small
 * observable store, register-replaces-by-id so HMR and plugin reloads stay
 * idempotent, and a stable snapshot for React's useSyncExternalStore.
 */
/** The minimum every registered definition provides: a unique, stable id. */
export interface RegistryDefinition {
	/** Unique id. Third-party entries should namespace ('vendor.package:media'). */
	id: string;
	/**
	 * Sort weight for listings (module launchers, the settings subnav). Lower
	 * comes first; entries with the same order keep registration order. Defaults
	 * to 100, leaving room for built-ins to sit before or after plugins.
	 */
	order?: number;
}
declare class ModalRegistry<Def extends RegistryDefinition> {
	private definitions;
	private listeners;
	private snapshot;
	/** Registering an already-known id replaces it, so HMR and plugin reloads stay idempotent. */
	register(definition: Def): void;
	unregister(id: string): void;
	get(id: string | null | undefined): Def | undefined;
	/**
	 * Stable snapshot sorted by `order` then registration order - changes
	 * identity only on (un)register, so useSyncExternalStore stays quiet.
	 */
	getAll(): Def[];
	subscribe(listener: () => void): () => void;
	private emit;
}
/** Icon type for a settings section - a bare Font Awesome name (e.g. "users"), resolved via faClassName. */
export type ModalIcon = string;
/**
 * A settings section: one entry in the shared Settings modal's subnavigation
 * (users, sites, workspaces, ...).
 */
export interface SettingsDialogDefinition extends RegistryDefinition {
	/** Label shown in the settings subnavigation and section header. */
	title: string;
	/** Optional subnav icon. */
	icon?: ModalIcon;
	/**
	 * Visual grouping in the subnavigation: a separator is drawn between
	 * adjacent sections whose groups differ. Sorting stays purely order-based,
	 * so keep a group's sections contiguous via their `order`. Omitting the
	 * group puts a section in the default (unnamed) group.
	 */
	group?: string;
	/** The section body. Propless - reads app state via context, like a settings screen. */
	component: React$1.ComponentType;
	/**
	 * A hook deciding whether this section is reachable right now (e.g. a
	 * permission check reading useMe()). When it returns false the section still
	 * appears in the subnavigation but disabled and unclickable - the host keeps
	 * it visible so users see the capability exists. Omit for always-enabled.
	 *
	 * It is a hook: the host calls it from a component dedicated to this section
	 * (one per subnav entry, and a remounted one for the body), so calling other
	 * hooks inside stays within the rules of hooks.
	 */
	useEnabled?: () => boolean;
	/** Tooltip shown on the disabled subnav entry, e.g. "Administrators only". */
	disabledReason?: string;
}
/**
 * The API version a plugin can read to feature-detect. Bump on a
 * breaking change to any exported type or registry contract; plugins that
 * care can compare against it before registering.
 */
export declare const version: 1;
/** Register/unregister panels. See {@link PanelDefinition}. */
export declare const panels: PanelRegistry;
/** Register/unregister inspector + creation-dialog property editors. See {@link PropertyEditorDefinition}. */
export declare const editors: PropertyEditorRegistry;
/** Register/unregister inspector views (read-only property visualisations). */
export declare const views: InspectorViewRegistry;
/** Register/unregister named property validators. */
export declare const validators: ValidatorRegistry;
/** Register/unregister link-editor type tabs. */
export declare const links: LinkEditorRegistry;
/** Register/unregister settings-dialog screens. */
export declare const modals: ModalRegistry<SettingsDialogDefinition>;
/** Options accepted by the toast helpers. */
export interface ToastOptions {
	/** Bold heading; defaults to a per-kind label ("Success", "Error", …). */
	title?: React$1.ReactNode;
	/** Auto-dismiss delay in ms. `0` keeps the toast until dismissed. */
	timeout?: number;
	/** Stable id - re-raising with the same id updates the toast in place. */
	id?: string;
}
/**
 * The app-wide toast API. Always prefer these over inline error/success
 * messages. This is the intentional public subset of the shell's toast helper.
 */
export interface ToastApi {
	success: (message: React$1.ReactNode, options?: ToastOptions) => string;
	info: (message: React$1.ReactNode, options?: ToastOptions) => string;
	loading: (message: React$1.ReactNode, options?: ToastOptions) => string;
	/** Accepts an Error / unknown and unwraps it to a message. */
	error: (message: unknown, options?: ToastOptions) => string;
	dismiss: (id?: string) => void;
}
export declare const toast: ToastApi;
/** The shape published at `window.NeosStudio` for plugin bundles to consume. */
export interface NeosStudioPluginApi {
	version: typeof version;
	panels: typeof panels;
	editors: typeof editors;
	views: typeof views;
	validators: typeof validators;
	links: typeof links;
	modals: typeof modals;
	useStudio: typeof useStudio;
	toast: typeof toast;
}
/**
 * Publish React and the plugin API on `window` so externalised plugin bundles
 * resolve them at runtime. Called once by the shell's entry module, before it
 * mounts and before any plugin script executes. Idempotent.
 */
export declare function installPluginApiGlobals(): void;

export {};
