import { executeCommands } from '@/api/commands'
import { queryKeys } from '@/api/keys'
import { addressFromContextPath, decodeNodeAddress } from '@/api/nodeAddress'
import { queryClient } from '@/app/queryClient'

/**
 * Structural node actions behind the preview's element menu and move-drag:
 * hide, unhide, delete and move. All operate on the viewed (covered)
 * dimension space point with the classic UI's strategies -
 * "allSpecializations" for hide/unhide/delete, "gatherAll" for moves - so no
 * variant creation is needed.
 */

export interface MoveNodeRequest {
  /** NodeAddress JSON of the element being moved. */
  nodeContextPath: string
  /** NodeAddress JSON of the target collection. */
  parentContextPath: string
  /** NodeAddress JSON of the sibling to insert before; null appends. */
  succeedingSiblingContextPath: string | null
}

/** One move for {@link moveNodesByAddress}, in encoded NodeAddress terms. */
export interface MoveByAddress {
  /** Encoded address of the node being moved. */
  nodeAddress: string
  /** Encoded address of the new parent. */
  newParentAddress: string
  /** Encoded address of the sibling to insert before; null appends. */
  succeedingSiblingAddress: string | null
}

export async function hideNode(address: string): Promise<void> {
  const node = decodeNodeAddress(address)
  await executeCommands([
    {
      type: 'DisableNodeAggregate',
      payload: {
        workspaceName: node.workspaceName,
        nodeAggregateId: node.aggregateId,
        coveredDimensionSpacePoint: node.dimensionSpacePoint,
        nodeVariantSelectionStrategy: 'allSpecializations',
      },
    },
  ])
  await invalidateAfterStructureChange()
}

/** Removes the "disabled" subtree tag set by hideNode. */
export async function unhideNode(address: string): Promise<void> {
  const node = decodeNodeAddress(address)
  await executeCommands([
    {
      type: 'EnableNodeAggregate',
      payload: {
        workspaceName: node.workspaceName,
        nodeAggregateId: node.aggregateId,
        coveredDimensionSpacePoint: node.dimensionSpacePoint,
        nodeVariantSelectionStrategy: 'allSpecializations',
      },
    },
  ])
  await invalidateAfterStructureChange()
}

/**
 * Changes a node's type. Uses the "happypath" conflict strategy: the change
 * applies only if the parent's and the node's descendants' constraints all
 * still hold, otherwise the command fails (rather than deleting offending
 * children). Tethered descendant ids for the new type are generated by the
 * server when omitted.
 */
export async function changeNodeType(
  address: string,
  newNodeTypeName: string,
): Promise<void> {
  const node = decodeNodeAddress(address)
  await executeCommands([
    {
      type: 'ChangeNodeAggregateType',
      payload: {
        workspaceName: node.workspaceName,
        nodeAggregateId: node.aggregateId,
        newNodeTypeName,
        strategy: 'happypath',
      },
    },
  ])
  await invalidateAfterStructureChange()
}

export async function deleteNode(address: string): Promise<void> {
  const node = decodeNodeAddress(address)
  await executeCommands([
    {
      type: 'RemoveNodeAggregate',
      payload: {
        workspaceName: node.workspaceName,
        nodeAggregateId: node.aggregateId,
        coveredDimensionSpacePoint: node.dimensionSpacePoint,
        nodeVariantSelectionStrategy: 'allSpecializations',
      },
    },
  ])
  await invalidateAfterStructureChange()
}

export async function moveNode(request: MoveNodeRequest): Promise<void> {
  const node = decodeNodeAddress(
    addressFromContextPath(request.nodeContextPath),
  )
  const parent = decodeNodeAddress(
    addressFromContextPath(request.parentContextPath),
  )
  const payload: Record<string, unknown> = {
    workspaceName: node.workspaceName,
    dimensionSpacePoint: node.dimensionSpacePoint,
    nodeAggregateId: node.aggregateId,
    newParentNodeAggregateId: parent.aggregateId,
    relationDistributionStrategy: 'gatherAll',
  }
  if (request.succeedingSiblingContextPath !== null) {
    payload.newSucceedingSiblingNodeAggregateId = decodeNodeAddress(
      addressFromContextPath(request.succeedingSiblingContextPath),
    ).aggregateId
  }
  await executeCommands([{ type: 'MoveNodeAggregate', payload }])
  await invalidateAfterStructureChange()
}

/**
 * Moves one or more nodes in a single batch, addressing them by their encoded
 * NodeAddress (what the trees carry as item ids) rather than the guest's JSON
 * context paths. Commands run in order, each placing its node before the same
 * succeeding sibling, so a multi-selection keeps its relative order at the
 * target ([A, B] before S becomes ...A, B, S). The viewed dimension is moved
 * with "gatherAll", like the preview's single-node move.
 */
export async function moveNodesByAddress(
  moves: MoveByAddress[],
): Promise<void> {
  if (moves.length === 0) return
  const commands = moves.map(
    ({ nodeAddress, newParentAddress, succeedingSiblingAddress }) => {
      const node = decodeNodeAddress(nodeAddress)
      const parent = decodeNodeAddress(newParentAddress)
      const payload: Record<string, unknown> = {
        workspaceName: node.workspaceName,
        dimensionSpacePoint: node.dimensionSpacePoint,
        nodeAggregateId: node.aggregateId,
        newParentNodeAggregateId: parent.aggregateId,
        relationDistributionStrategy: 'gatherAll',
      }
      if (succeedingSiblingAddress !== null) {
        payload.newSucceedingSiblingNodeAggregateId = decodeNodeAddress(
          succeedingSiblingAddress,
        ).aggregateId
      }
      return { type: 'MoveNodeAggregate', payload }
    },
  )
  await executeCommands(commands)
  await invalidateAfterStructureChange()
}

/**
 * Children lists changed - drop all node reads (children are keyed under
 * nodes) and refresh the pending-changes badges.
 */
async function invalidateAfterStructureChange(): Promise<void> {
  await queryClient.invalidateQueries({ queryKey: queryKeys.nodes.all })
  void queryClient.invalidateQueries({ queryKey: queryKeys.workspaces.all })
}
